### ISSUE TITLE
IR Sensor Interface

### ISSUE THREAD

**Issue by mikeshams** [ShivinderK/Capstone_Project#3]
What issues did you face and how to reslove?

**Comment by Dawinderkaur** [comment]
1. While cloning git repository for GPIO library forgets to give ethernet connection to BBB. Error came up as connection failed when i ping google.com
2. I connect the LED pin to pin 11 of the P8 header BBB but it was not glowing as per c code so I replace it with pin 12 of the P8 header.
3. While defining the pin for IR sensor and LED to BBB i define it as “#define LEDpin 12,8” i got error “segmentation fault” . then i changed it to “#define LEDpin 8,12”.so pins are defined as "pin header, pin number"
4. Getting output of c code in continuous flow on terminal. so to make it understand i add some dealy using usleep function in c program.
5. Forget to add POSIX API library at first due to which i get error at usleep function. so i include those library in c program header and error got resolved.
