### ISSUE TITLE
ESP32 Interface

### ISSUE THREAD

**Issue by mikeshams** [ShivinderK/Capstone_Project#4]
What issues did you face and how to resolve?

**Comment by ShivinderK** [comment]
1. With Arduino IDE when I was uploading the code on ESP32 board it was showing error and not getting connected to the board. Then from this link https://randomnerdtutorials.com/installing-the-esp32-board-in-arduino-ide-windows-instructions/, I got to know that while uploading the code I have to the press the boot button and then when it starts showing connecting then release the boot button slowly and it will get connected.

**Comment by ShivinderK** [comment]
2. The problem I was getting in the first code was when I was uploading the code to the board it was giving the IP address but the webpage was not opening successfully because of the timeout problem. Then I resolved this issue from this link matlab.com/question/solved-esp32-web-server-drops-connection-crashes/  and then I was able to get the access to the webpage.
3. Then I tested our webpage by connecting the LEDs directly to esp32 board pins 26 and 27 and it successfully giving output by pressing the buttons on webpage.
4. Then I connected the LEDs and esp32 pins to the beaglebone. But the wrong thing I did was the pin that I have to make as an input I made it as output and the output pin as input. So when I was running my code it was not working but it was working when I was connecting the LEDs directly to the esp32. I resolved this issue by defining the pins correctly.
5. Then I was getting problem with if else loop. Then I resolved this issue from this link that how I can properly use the if else loop https://www.programiz.com/c-programming/c-if-else-statement
6. Also while performing I got to know that when I have to upload the code to ESP32, only ESP32 should be connected to the system and not even beaglebone or jumper wires should be connected, otherwise they will create interference while uploading the code to the board.

**Comment by mikeshams** [comment]
Do a little research how to check the wifi signal strength using your wifi module?

**Comment by mikeshams** [comment]
Do a little research how to check the wifi signal strength using your wifi module?

**Comment by mikeshams** [comment]
Do a little research how to check the wifi signal strength using your wifi module?

**Comment by mikeshams** [comment]
Do a little research how to check the wifi signal strength using your wifi module?

**Comment by mikeshams** [comment]
Do a little research how to check the wifi signal strength using your wifi module?

**Comment by ShivinderK** [comment]
7. To check the signal strength I can add this syntax  WiFi.RSSI() and this code provided in this link https://randomnerdtutorials.com/esp32-useful-wi-fi-functions-arduino/  in the program. That will provide the signal strength in he output.
